### PR TITLE
remove constraint on haml version

### PR DESCRIPTION
**Pull request by lostapathy**
flay-haml seems to work fine with haml 5.

### CODE REVIEW

**Comment by UncleGene** [comment]
Thanks you!
Will trust you on this :)

**Comment by lostapathy** [comment]
Thanks @UncleGene - when you have time, cutting a new version of the gem to include the change would be appreciated.

**Comment by UncleGene** [comment]
Done

**Comment by lostapathy** [comment]
The constraint you added of
```
s.add_dependency 'haml', '>= 3', '<=5'
```
prevents flay-haml from installing with haml 5.0.1.  If you want to bound the upper version, you probably want more like this?
```
s.add_dependency 'haml', '>= 3', '<6'
```

thanks!

**Comment by UncleGene** [comment]
Oops, my bad. Will fix and re-publish

**Pull request merged**
